### ISSUE TITLE
local authentication bug with users as sequelize service

### ISSUE THREAD

**Issue by jarnojellesma** [feathersjs/authentication-local#47]
### Expected behavior
Authenticate user

### Actual behavior
```
className: "general-error"
code: 500
data: Object {  }
errors: Object {  }
message: "the `id` property must be set on the entity service for authentication"
name: "GeneralError"
stack: "FeathersError@http://localhost:3000/_nuxt/app.e42a4ab34fc5e966dc8b.js:8069:19\nGeneralError@http://localhost:3000/_nuxt/app.e42a4ab34fc5e966dc8b.js:8176:3\nconvert@http://localhost:3000/_nuxt/app.e42a4ab34fc5e966dc8b.js:8245:7\ntoError@http://localhost:3000/_nuxt/app.e42a4ab34fc5e966dc8b.js:8392:9\n"
type: "FeathersError"
```

### How I solved it
@feathersjs/authentication-local in lib/verifier.js:

Add `this.service.id = this.service.sequelize.id` in the constructor.

```
class LocalVerifier {
  constructor (app, options = {}) {
    this.app = app;
    this.options = options;
    this.service = typeof options.service === 'string' ? app.service(options.service) : options.service;
    this.service.id = this.service.sequelize.id; // <--- this line

    if (!this.service) {
      throw new Error(`options.service does not exist.\n\tMake sure you are passing a valid service path or service instance and it is initialized before @feathersjs/authentication-local.`);
    }

    this._comparePassword = this._comparePassword.bind(this);
    this._normalizeResult = this._normalizeResult.bind(this);
    this.verify = this.verify.bind(this);
  }
```

### System configuration

"@feathersjs/authentication": "^2.1.0",
    "@feathersjs/authentication-jwt": "^1.0.1",
    "@feathersjs/authentication-local": "^1.0.2",
    "@feathersjs/authentication-oauth2": "^1.0.2",
    "@feathersjs/configuration": "^1.0.1",
    "@feathersjs/errors": "^3.2.0",
    "@feathersjs/express": "^1.1.2",
    "@feathersjs/feathers": "^3.0.2",

**Comment by daffl** [comment]
The `id` property for a `feathers-sequelize` service is being set [here](https://github.com/feathersjs-ecosystem/feathers-sequelize/blob/master/lib/index.js#L20) so it should be available. Is this a normal setup with that adapter?

**Comment by jarnojellesma** [comment]
Ah I see, I am using a custom class on top of the feathers-sequelize class and I didn't add that line of code there. Thanks!

**Comment by daffl** [comment]
If you have a custom constructor, this should also be solvable by calling `super(options)` in it.
