### ISSUE TITLE
protect hook attempts to map through 'result.data' on all service methods.

### ISSUE THREAD

**Issue by ppatel890** [feathersjs/authentication-local#53]
### Steps to reproduce

Add 'protect' hook to all service methods for any specific method.

### Expected behavior
On get, update, patch, the hook should only act on the single object returned. On find method, if result.data exists, map over result.data and run hook on every object in array.

### Actual behavior
The hook attempts to map over 'result.data', even if the service method was not find.

**Comment by daffl** [comment]
Fixed in version 1.1.0
