### ISSUE TITLE
Protect hooks does not support dot notation

### ISSUE THREAD

**Issue by bertho-zero** [feathersjs/authentication-local#61]
I can not protect my field `author.password` after a fastJoin and `local.hooks.protect`.

https://github.com/lodash/lodash/issues/3754

The problem here is that the package 'lodash.omit' does not support dot notation:
https://github.com/feathersjs/authentication-local/blob/aec93424d3181b55679919821eeeb31354f1114d/lib/hooks/protect.js#L9

___

The `local.hooks.protect` of the users service call in my fastJoin resolver does not omit the password due to the missing provider params, and if I provide them I do not pass my authentication hooks for external calls. 

https://github.com/feathersjs/authentication-local/blob/aec93424d3181b55679919821eeeb31354f1114d/lib/hooks/protect.js#L26-L28

**Comment by daffl** [comment]
Fixed in v1.1.2
